version: "3"

x-celery-env: &celery-env
  AIRFLOW__CORE__EXECUTOR: CeleryExecutor
  AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
  AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://postgres:postgres@postgres:5432/postgres
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@postgres:5432/postgres

services:
  scheduler:
    environment:
      <<: *celery-env

  api-server:
    environment:
      <<: *celery-env

  triggerer:
    environment:
      <<: *celery-env

  dag-processor:
    environment:
      <<: *celery-env

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - airflow_124371_default
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 30s
      retries: 50

  airflow-worker:
    image: airflow_124371/airflow:latest
    restart: always
    depends_on:
      - redis
    environment:
      <<: *celery-env
    networks:
      - airflow_124371_default
    command: airflow celery worker

  flower:
    image: airflow_124371/airflow:latest
    restart: always
    depends_on:
      - redis
    ports:
      - "5555:5555"
    environment:
      <<: *celery-env
    command: airflow celery flower
    networks:
      - airflow_124371_default

networks:
  airflow_124371_default:
    external: true
